// English destination name map for WanderNote globalization.
// Batch 1: countries / regions.
// Later batches will append cities.
// Source of truth for display fallback in non-Chinese UI.

export const DESTINATION_EN = {
  '不丹': 'Bhutan',
  '东帝汶': 'Timor-Leste',
  '中国': 'China',
  '丹麦': 'Denmark',
  '乌克兰': 'Ukraine',
  '乌兹别克斯坦': 'Uzbekistan',
  '乌干达': 'Uganda',
  '乌拉圭': 'Uruguay',
  '也门': 'Yemen',
  '亚美尼亚': 'Armenia',
  '以色列': 'Israel',
  '伊朗': 'Iran',
  '伯利兹': 'Belize',
  '俄罗斯': 'Russia',
  '保加利亚': 'Bulgaria',
  '克罗地亚': 'Croatia',
  '冰岛': 'Iceland',
  '列支敦士登': 'Liechtenstein',
  '加拿大': 'Canada',
  '加纳': 'Ghana',
  '匈牙利': 'Hungary',
  '北极地区': 'Arctic Region',
  '北马其顿': 'North Macedonia',
  '南极洲': 'Antarctica',
  '南非': 'South Africa',
  '博茨瓦纳': 'Botswana',
  '卡塔尔': 'Qatar',
  '卢旺达': 'Rwanda',
  '卢森堡': 'Luxembourg',
  '印度': 'India',
  '印度尼西亚': 'Indonesia',
  '危地马拉': 'Guatemala',
  '厄瓜多尔': 'Ecuador',
  '叙利亚': 'Syria',
  '古巴': 'Cuba',
  '台湾': 'Taiwan',
  '吉尔吉斯斯坦': 'Kyrgyzstan',
  '哈萨克斯坦': 'Kazakhstan',
  '哥伦比亚': 'Colombia',
  '哥斯达黎加': 'Costa Rica',
  '图瓦卢': 'Tuvalu',
  '土库曼斯坦': 'Turkmenistan',
  '土耳其': 'Turkey',
  '圣马力诺': 'San Marino',
  '圭亚那': 'Guyana',
  '坦桑尼亚': 'Tanzania',
  '埃及': 'Egypt',
  '埃塞俄比亚': 'Ethiopia',
  '基里巴斯': 'Kiribati',
  '塔吉克斯坦': 'Tajikistan',
  '塞内加尔': 'Senegal',
  '塞尔维亚': 'Serbia',
  '塞浦路斯': 'Cyprus',
  '塞舌尔': 'Seychelles',
  '墨西哥': 'Mexico',
  '多米尼加': 'Dominican Republic',
  '奥地利': 'Austria',
  '委内瑞拉': 'Venezuela',
  '孟加拉国': 'Bangladesh',
  '安道尔': 'Andorra',
  '密克罗尼西亚': 'Federated States of Micronesia',
  '尼加拉瓜': 'Nicaragua',
  '尼泊尔': 'Nepal',
  '巴基斯坦': 'Pakistan',
  '巴布亚新几内亚': 'Papua New Guinea',
  '巴拉圭': 'Paraguay',
  '巴拿马': 'Panama',
  '巴林': 'Bahrain',
  '巴西': 'Brazil',
  '希腊': 'Greece',
  '帕劳': 'Palau',
  '德国': 'Germany',
  '意大利': 'Italy',
  '所罗门群岛': 'Solomon Islands',
  '拉脱维亚': 'Latvia',
  '挪威': 'Norway',
  '捷克': 'Czechia',
  '摩尔多瓦': 'Moldova',
  '摩洛哥': 'Morocco',
  '摩纳哥': 'Monaco',
  '文莱': 'Brunei',
  '斐济': 'Fiji',
  '斯洛伐克': 'Slovakia',
  '斯洛文尼亚': 'Slovenia',
  '斯瓦尔巴群岛(挪威)': 'Svalbard (Norway)',
  '斯里兰卡': 'Sri Lanka',
  '新加坡': 'Singapore',
  '新西兰': 'New Zealand',
  '日本': 'Japan',
  '智利': 'Chile',
  '朝鲜': 'North Korea',
  '柬埔寨': 'Cambodia',
  '格陵兰(丹麦)': 'Greenland (Denmark)',
  '格鲁吉亚': 'Georgia',
  '梵蒂冈': 'Vatican City',
  '比利时': 'Belgium',
  '毛里求斯': 'Mauritius',
  '汤加': 'Tonga',
  '沙特阿拉伯': 'Saudi Arabia',
  '法国': 'France',
  '法属波利尼西亚/塔希提': 'French Polynesia / Tahiti',
  '波兰': 'Poland',
  '波黑': 'Bosnia and Herzegovina',
  '泰国': 'Thailand',
  '津巴布韦': 'Zimbabwe',
  '洪都拉斯': 'Honduras',
  '澳大利亚': 'Australia',
  '澳门': 'Macau',
  '爱尔兰': 'Ireland',
  '爱沙尼亚': 'Estonia',
  '牙买加': 'Jamaica',
  '玻利维亚': 'Bolivia',
  '瑙鲁': 'Nauru',
  '瑞典': 'Sweden',
  '瑞士': 'Switzerland',
  '瓦努阿图': 'Vanuatu',
  '留尼汪': 'Réunion',
  '白俄罗斯': 'Belarus',
  '科威特': 'Kuwait',
  '科索沃': 'Kosovo',
  '秘鲁': 'Peru',
  '突尼斯': 'Tunisia',
  '立陶宛': 'Lithuania',
  '约旦': 'Jordan',
  '纳米比亚': 'Namibia',
  '缅甸': 'Myanmar',
  '罗马尼亚': 'Romania',
  '美国': 'United States',
  '老挝': 'Laos',
  '肯尼亚': 'Kenya',
  '芬兰': 'Finland',
  '苏里南': 'Suriname',
  '英国': 'United Kingdom',
  '荷兰': 'Netherlands',
  '菲律宾': 'Philippines',
  '萨摩亚': 'Samoa',
  '葡萄牙': 'Portugal',
  '蒙古': 'Mongolia',
  '西班牙': 'Spain',
  '赞比亚': 'Zambia',
  '越南': 'Vietnam',
  '阿塞拜疆': 'Azerbaijan',
  '阿富汗': 'Afghanistan',
  '阿尔巴尼亚': 'Albania',
  '阿拉斯加(美国)': 'Alaska (United States)',
  '阿曼': 'Oman',
  '阿根廷': 'Argentina',
  '阿联酋': 'United Arab Emirates',
  '韩国': 'South Korea',
  '香港': 'Hong Kong',
  '马尔代夫': 'Maldives',
  '马来西亚': 'Malaysia',
  '马绍尔群岛': 'Marshall Islands',
  '马耳他': 'Malta',
  '马达加斯加': 'Madagascar',
  '黎巴嫩': 'Lebanon',
  '黑山': 'Montenegro',
  '4000岛': '4000 Islands',
  '万基国家公园': 'Hwange National Park',
  '万象': 'Vientiane',
  '三亚': 'Sanya',
  '上海': 'Shanghai',
  '东京': 'Tokyo',
  '东格陵兰': 'East Greenland',
  '中卡拉哈里': 'Central Kalahari',
  '丽江': 'Lijiang',
  '乌兰巴托': 'Ulaanbaatar',
  '乌斯怀亚/世界尽头': 'Ushuaia / End of the World',
  '乌鲁鲁/艾尔斯岩': 'Uluru / Ayers Rock',
  '乔治敦': 'Georgetown',
  '乔贝': 'Chobe',
  '九份': 'Jiufen',
  '九龙': 'Kowloon',
  '乞力马扎罗': 'Kilimanjaro',
  '亚伦': 'Yaren',
  '亚历山大': 'Alexandria',
  '亚喀巴': 'Aqaba',
  '亚松森': 'Asunción',
  '亚的斯亚贝巴': 'Addis Ababa',
  '亚速尔群岛': 'Azores',
  '亚马逊/马瑙斯': 'Amazon / Manaus',
  '亚马逊雨林': 'Amazon Rainforest',
  '京都': 'Kyoto',
  '仁川': 'Incheon',
  '代尔夫特': 'Delft',
  '仰光': 'Yangon',
  '伊卢利萨特冰湾': 'Ilulissat Icefjord',
  '伊塞克湖': 'Issyk-Kul Lake',
  '伊斯兰堡': 'Islamabad',
  '伊斯坦布尔': 'Istanbul',
  '伦敦': 'London',
  '伯利兹城': 'Belize City',
  '佛罗伦萨': 'Florence',
  '克拉科夫': 'Kraków',
  '克莱佩达': 'Klaipėda',
  '克鲁格公园': 'Kruger National Park',
  '全州': 'Jeonju',
  '兰卡威': 'Langkawi',
  '内罗毕': 'Nairobi',
  '冲绳': 'Okinawa',
  '凯恩斯': 'Cairns',
  '利沃夫': 'Lviv',
  '利雅得': 'Riyadh',
  '利马': 'Lima',
  '利马索尔': 'Limassol',
  '剑桥': 'Cambridge',
  '加巴拉': 'Gabala',
  '加德满都': 'Kathmandu',
  '努克': 'Nuuk',
  '努库阿洛法': 'Nukuʻalofa',
  '北京': 'Beijing',
  '北极点': 'North Pole',
  '北极熊观测地': 'Polar Bear Watching Area',
  '北海道': 'Hokkaido',
  '北马累环礁': 'North Malé Atoll',
  '半岛地区': 'Peninsula Region',
  '华欣': 'Hua Hin',
  '华沙': 'Warsaw',
  '卑尔根': 'Bergen',
  '南乔治亚岛': 'South Georgia Island',
  '南卢安瓜': 'South Luangwa',
  '南塔拉瓦': 'South Tarawa',
  '南岸': 'South Bank',
  '南极点': 'South Pole',
  '南迪': 'Nadi',
  '南马累环礁': 'South Malé Atoll',
  '博卡拉': 'Pokhara',
  '博卡斯德尔托罗': 'Bocas del Toro',
  '博恩霍尔姆岛': 'Bornholm',
  '博霍尔': 'Bohol',
  '卡奈马': 'Canaima',
  '卡拉奇': 'Karachi',
  '卡萨布兰卡': 'Casablanca',
  '卢克索': 'Luxor',
  '卢布尔雅那': 'Ljubljana',
  '卢森堡城': 'Luxembourg City',
  '厦门': 'Xiamen',
  '台中': 'Taichung',
  '台北': 'Taipei',
  '台南': 'Tainan',
  '吉大港': 'Chittagong',
  '吉诺卡斯特': 'Gjirokastër',
  '吉达': 'Jeddah',
  '吉隆坡': 'Kuala Lumpur',
  '吴哥窟/暹粒': 'Angkor Wat / Siem Reap',
  '哈瓦那': 'Havana',
  '哥德堡': 'Gothenburg',
  '哥本哈根': 'Copenhagen',
  '喀布尔': 'Kabul',
  '喀比': 'Krabi',
  '因斯布鲁克': 'Innsbruck',
  '图卢姆': 'Tulum',
  '图尔库': 'Turku',
  '圣但尼': 'Saint-Denis',
  '圣何塞': 'San José',
  '圣保罗': 'São Paulo',
  '圣克里斯托瓦尔': 'San Cristóbal',
  '万荣': 'Vang Vieng',
  '下龙湾': 'Ha Long Bay',
  '乌尤尼盐湖': 'Salar de Uyuni',
  '五渔村': 'Cinque Terre',
  '亚兹德': 'Yazd',
  '以弗所': 'Ephesus',
  '伊斯法罕': 'Isfahan',
  '伊瓜苏瀑布': 'Iguazu Falls',
  '会安': 'Hoi An',
  '佩特拉': 'Petra',
  '克里特岛': 'Crete',
  '克鲁姆洛夫': 'Český Krumlov',
  '冰川湾': 'Glacier Bay',
  '加勒': 'Galle',
  '加拉帕戈斯群岛': 'Galápagos Islands',
  '博德鲁姆': 'Bodrum',
  '卡伊图尔瀑布': 'Kaieteur Falls',
  '卡兹别吉': 'Kazbegi',
  '卡塔赫纳': 'Cartagena',
  '卡帕多奇亚': 'Cappadocia',
  '卡罗维发利': 'Karlovy Vary',
  '咖啡产区': 'Coffee Region',
  '哈尔施塔特': 'Hallstatt',
  '喀拉拉邦': 'Kerala',
  '因特拉肯': 'Interlaken',
  '圣地亚哥': 'Santiago',
  '圣塞巴斯蒂安': 'San Sebastián',
  '圣多明各': 'Santo Domingo',
  '圣布拉斯群岛': 'San Blas Islands',
  '圣彼得堡': 'Saint Petersburg',
  '圣托里尼': 'Santorini',
  '圣路易': 'Saint-Louis',
  '圣马力诺城': 'San Marino City',
  '地拉那': 'Tirana',
  '地狱之门/达瓦扎': 'Darvaza Gas Crater / Door to Hell',
  '坎帕拉': 'Kampala',
  '坎昆': 'Cancún',
  '坦佩雷': 'Tampere',
  '坦纳岛火山': 'Tanna Island Volcano',
  '垦丁': 'Kenting',
  '埃托沙': 'Etosha National Park',
  '埃斯特角城': 'Punta del Este',
  '埃格尔': 'Eger',
  '埃里温': 'Yerevan',
  '培拉特': 'Berat',
  '基伍湖': 'Lake Kivu',
  '基加利': 'Kigali',
  '基多': 'Quito',
  '基希讷乌': 'Chișinău',
  '基拉尼': 'Killarney',
  '基督城': 'Christchurch',
  '基辅': 'Kyiv',
  '堪察加': 'Kamchatka',
  '塔什干': 'Tashkent',
  '塔尔图': 'Tartu',
  '塔斯马尼亚': 'Tasmania',
  '塔林': 'Tallinn',
  '塔那那利佛': 'Antananarivo',
  '塞伦盖蒂': 'Serengeti',
  '塞凡湖': 'Lake Sevan',
  '塞维利亚': 'Seville',
  '墨尔本': 'Melbourne',
  '墨西哥城': 'Mexico City',
  '复活节岛': 'Easter Island',
  '夏威夷': 'Hawaii',
  '多伦多': 'Toronto',
  '多哈': 'Doha',
  '多瑙河三角洲': 'Danube Delta',
  '大叻': 'Da Lat',
  '大城': 'Ayutthaya',
  '大堡礁': 'Great Barrier Reef',
  '大屿山': 'Lantau Island',
  '大峡谷': 'Grand Canyon',
  '大特尔诺沃': 'Veliko Tarnovo',
  '大理': 'Dali',
  '大阪': 'Osaka',
  '大马士革': 'Damascus',
  '天空之镜': 'Mirror of the Sky',
  '奇姆肯特': 'Shymkent',
  '奇特旺': 'Chitwan',
  '奈良': 'Nara',
  '奥什': 'Osh',
  '奥克兰': 'Auckland',
  '奥卡万戈三角洲': 'Okavango Delta',
  '奥塔瓦洛': 'Otavalo',
  '奥斯陆': 'Oslo',
  '奥胡斯': 'Aarhus',
  '奥赫里德': 'Ohrid',
  '威尼斯': 'Venice',
  '威灵顿': 'Wellington',
  '孙德尔本斯': 'Sundarbans',
  '孟买': 'Mumbai',
  '安伯格里斯岛': 'Ambergris Caye',
  '安博塞利': 'Amboseli National Park',
  '安塔利亚': 'Antalya',
  '安提瓜': 'Antigua',
  '安曼': 'Amman',
  '安特卫普': 'Antwerp',
  '安赫尔瀑布': 'Angel Falls',
  '安道尔城': 'Andorra la Vella',
  '宿务': 'Cebu',
  '富国岛': 'Phu Quoc',
  '富纳富提': 'Funafuti',
  '少女峰': 'Jungfrau',
  '尤卡斯耶尔维/冰旅馆': 'Jukkasjärvi / Icehotel',
  '尤尔马拉': 'Jūrmala',
  '尼什': 'Niš',
  '尼兹瓦': 'Nizwa',
  '尼斯': 'Nice',
  '尼格里尔': 'Negril',
  '尼科西亚': 'Nicosia',
  '岘港': 'Da Nang',
  '峡湾国家公园': 'Fiordland National Park',
  '巴勒贝克': 'Baalbek',
  '巴厘岛': 'Bali',
  '巴塔哥尼亚': 'Patagonia',
  '巴塞罗那': 'Barcelona',
  '巴库': 'Baku',
  '巴拉德罗': 'Varadero',
  '巴拉望岛': 'Palawan',
  '巴拿马城': 'Panama City',
  '巴斯': 'Bath',
  '巴米扬': 'Bamiyan',
  '巴统': 'Batumi',
  '巴黎': 'Paris',
  '布列斯特': 'Brest',
  '布加勒斯特': 'Bucharest',
  '布哈拉': 'Bukhara',
  '布宜诺斯艾利斯': 'Buenos Aires',
  '布尔诺': 'Brno',
  '布德瓦': 'Budva',
  '布拉格': 'Prague',
  '布拉索夫': 'Brașov',
  '布拉迪斯拉发': 'Bratislava',
  '布温迪': 'Bwindi Impenetrable National Park',
  '布莱德湖': 'Lake Bled',
  '布达佩斯': 'Budapest',
  '布里斯班': 'Brisbane',
  '布鲁塞尔': 'Brussels',
  '布鲁日': 'Bruges',
  '希瓦': 'Khiva',
  '帕尔米拉': 'Palmyra',
  '帕拉马里博': 'Paramaribo',
  '帕皮提': 'Papeete',
  '帕福斯': 'Paphos',
  '帕米尔高原': 'Pamir Mountains',
  '帕罗': 'Paro',
  '帝力': 'Dili',
  '平壤': 'Pyongyang',
  '广岛': 'Hiroshima',
  '庆州': 'Gyeongju',
  '库塔伊西': 'Kutaisi',
  '库延卡': 'Cuenca',
  '库斯科': 'Cusco',
  '库苏古尔湖': 'Lake Khövsgöl',
  '库马西': 'Kumasi',
  '康提': 'Kandy',
  '廷布': 'Thimphu',
  '开普敦': 'Cape Town',
  '开普科斯特': 'Cape Coast',
  '开罗/吉萨金字塔': 'Cairo / Giza Pyramids',
  '弗朗茨约瑟夫地群岛': 'Franz Josef Land',
  '弗洛姆': 'Flåm',
  '弗罗茨瓦夫': 'Wrocław',
  '张家界': 'Zhangjiajie',
  '彩虹山': 'Rainbow Mountain',
  '德拉肯斯堡': 'Drakensberg',
  '德累斯顿': 'Dresden',
  '德里': 'Delhi',
  '德黑兰': 'Tehran',
  '恩戈罗恩戈罗': 'Ngorongoro',
  '悉尼': 'Sydney',
  '慕尼黑': 'Munich',
  '戈佐岛': 'Gozo',
  '戈壁沙漠': 'Gobi Desert',
  '戈尔韦': 'Galway',
  '戈罗卡': 'Goroka',
  '戈雷岛': 'Gorée Island',
  '成都': 'Chengdu',
  '扎科帕内': 'Zakopane',
  '扎达尔': 'Zadar',
  '托尔图格罗': 'Tortuguero',
  '托雷斯德尔潘恩': 'Torres del Paine',
  '拉利贝拉': 'Lalibela',
  '拉合尔': 'Lahore',
  '拉巴斯': 'La Paz',
  '拉斯维加斯': 'Las Vegas',
  '拉穆岛': 'Lamu Island',
  '拉萨': 'Lhasa',
  '拉达克': 'Ladakh',
  '拉迪格岛': 'La Digue',
  '拜布洛斯': 'Byblos',
  '摩纳哥城': 'Monaco City',
  '撒哈拉/杜兹': 'Sahara / Douz',
  '撒马尔罕': 'Samarkand',
  '敖德萨': 'Odesa',
  '敦煌': 'Dunhuang',
  '斋浦尔': 'Jaipur',
  '斯奈山半岛': 'Sinai Peninsula',
  '斯德哥尔摩': 'Stockholm',
  '斯普利特': 'Split',
  '斯特拉斯堡': 'Strasbourg',
  '斯科普里': 'Skopje',
  '斯里巴加湾市': 'Bandar Seri Begawan',
  '新天鹅堡': 'Neuschwanstein Castle',
  '新奥尔松': 'Ny-Ålesund',
  '新奥尔良': 'New Orleans',
  '日内瓦': 'Geneva',
  '日惹': 'Yogyakarta',
  '日月潭': 'Sun Moon Lake',
  '旧金山': 'San Francisco',
  '明斯克': 'Minsk',
  '普利特维采': 'Plitvice Lakes',
  '普吉岛': 'Phuket',
  '普拉斯林岛': 'Praslin Island',
  '普纳卡': 'Punakha',
  '普罗夫迪夫': 'Plovdiv',
  '普罗旺斯': 'Provence',
  '普里什蒂纳': 'Pristina',
  '普里兹伦': 'Prizren',
  '曼德勒': 'Mandalay',
  '曼谷': 'Bangkok',
  '朗伊尔城': 'Longyearbyen',
  '杜尚别': 'Dushanbe',
  '杜布罗夫尼克': 'Dubrovnik',
  '杭州': 'Hangzhou',
  '果阿': 'Goa',
  '柏林': 'Berlin',
  '根特': 'Ghent',
  '格但斯克': 'Gdańsk',
  '格加尔德': 'Geghard',
  '格拉纳达': 'Granada',
  '桂林': 'Guilin',
  '桑给巴尔': 'Zanzibar',
  '梅尔祖卡沙漠': 'Merzouga Desert',
  '梵蒂冈城': 'Vatican City',
  '棉花堡': 'Pamukkale',
  '楚克泻湖': 'Chuuk Lagoon',
  '槟城': 'Penang',
  '死海': 'Dead Sea',
  '比什凯克': 'Bishkek',
  '比尼亚莱斯': 'Viñales',
  '毕尔巴鄂': 'Bilbao',
  '氹仔': 'Taipa',
  '汉堡': 'Hamburg',
  '沙巴': 'Sabah',
  '沙拉拉': 'Salalah',
  '沙迦': 'Sharjah',
  '河内': 'Hanoi',
  '法罗群岛': 'Faroe Islands',
  '波哥大': 'Bogotá',
  '波士顿': 'Boston',
  '波尔图': 'Porto',
  '波尔多': 'Bordeaux',
  '波德戈里察': 'Podgorica',
  '波托西': 'Potosí',
  '波拉波拉岛': 'Bora Bora',
  '波斯托伊纳洞穴': 'Postojna Cave',
  '泰姬陵/阿格拉': 'Taj Mahal / Agra',
  '洛斯罗克斯群岛': 'Los Roques Archipelago',
  '洛杉矶': 'Los Angeles',
  '洪扎谷地': 'Hunza Valley',
  '济州岛': 'Jeju Island',
  '海德堡': 'Heidelberg',
  '海法': 'Haifa',
  '海牙': 'The Hague',
  '清奈': 'Chennai',
  '清莱': 'Chiang Rai',
  '清迈': 'Chiang Mai',
  '温哥华': 'Vancouver',
  '温得和克': 'Windhoek',
  '湖区': 'Lake District',
  '澳门半岛': 'Macau Peninsula',
  '火山国家公园': 'Volcanoes National Park',
  '爱丁堡': 'Edinburgh',
  '牛津': 'Oxford',
  '特拉维夫': 'Tel Aviv',
  '特立尼达': 'Trinidad',
  '特罗姆瑟': 'Tromsø',
  '玛玛努卡群岛': 'Mamanuca Islands',
  '珀斯': 'Perth',
  '珠峰大本营': 'Everest Base Camp',
  '班夫': 'Banff',
  '班达米尔湖': 'Band-e Amir Lakes',
  '琅勃拉邦': 'Luang Prabang',
  '琉森': 'Lucerne',
  '瓦伦西亚': 'Valencia',
  '瓦哈卡': 'Oaxaca',
  '瓦尔帕莱索': 'Valparaíso',
  '瓦希巴沙漠': 'Wahiba Sands',
  '瓦拉纳西': 'Varanasi',
  '瓦杜兹': 'Vaduz',
  '瓦瓦乌群岛': 'Vavaʻu',
  '瓦莱塔': 'Valletta',
  '瓦迪拉姆': 'Wadi Rum',
  '白川乡': 'Shirakawa-go',
  '的的喀喀湖': 'Lake Titicaca',
  '皇后镇': 'Queenstown',
  '皮通德拉富尔内斯火山': 'Piton de la Fournaise',
  '盖朗厄尔峡湾': 'Geirangerfjord',
  '石头岛': 'Stone Town',
  '神户': 'Kobe',
  '福冈': 'Fukuoka',
  '离岛': 'Outlying Islands',
  '科伦坡': 'Colombo',
  '科克': 'Cork',
  '科威特城': 'Kuwait City',
  '科孚岛': 'Corfu',
  '科托尔': 'Kotor',
  '科洛尼亚': 'Colonia del Sacramento',
  '科潘遗址': 'Copán Ruins',
  '科罗尔': 'Koror',
  '科苏梅尔岛': 'Koh Samui',
  '科茨沃尔德': 'Cotswolds',
  '科莫多岛': 'Komodo Island',
  '科西嘉岛': 'Corsica',
  '科隆': 'Cologne',
  '穆尔奇森瀑布': 'Murchison Falls',
  '穆龙达瓦': 'Morondava',
  '突尼斯城': 'Tunis',
  '第比利斯': 'Tbilisi',
  '箱根': 'Hakone',
  '米兰': 'Milan',
  '米科诺斯': 'Mykonos',
  '索契': 'Sochi',
  '索科特拉岛': 'Socotra Island',
  '索维拉': 'Essaouira',
  '索非亚': 'Sofia',
  '红海/赫尔格达': 'Red Sea / Hurghada',
  '约克': 'York',
  '约翰内斯堡': 'Johannesburg',
  '纳什维尔': 'Nashville',
  '纳米布沙漠': 'Namib Desert',
  '纽约': 'New York',
  '维也纳': 'Vienna',
  '维多利亚': 'Victoria',
  '维多利亚瀑布': 'Victoria Falls',
  '维多利亚瀑布/利文斯通': 'Victoria Falls / Livingstone',
  '维安登': 'Vianden',
  '维尔纽斯': 'Vilnius',
  '维拉港': 'Port Vila',
  '维提岛': 'Viti Levu',
  '罗弗敦群岛': 'Lofoten Islands',
  '罗德岛': 'Rhodes',
  '罗德里格斯岛': 'Rodrigues Island',
  '罗托鲁阿': 'Rotorua',
  '罗瓦涅米/圣诞老人村': 'Rovaniemi / Santa Claus Village',
  '罗腾堡': 'Rothenburg ob der Tauber',
  '罗阿坦岛': 'Roatán',
  '罗马': 'Rome',
  '羊角村': 'Giethoorn',
  '考纳斯': 'Kaunas',
  '耶路撒冷': 'Jerusalem',
  '育空': 'Yukon',
  '胡志明市': 'Ho Chi Minh City',
  '舍基': 'Sheki',
  '舍夫沙万': 'Chefchaouen',
  '芝加哥': 'Chicago',
  '花园大道': 'Garden Route',
  '花莲': 'Hualien',
  "芽庄": "Nha Trang",
  "苏州": "Suzhou",
  "苏格兰高地": "Scottish Highlands",
  "苏梅岛": "Koh Samui",
  "苏黎世": "Zurich",
  "茵莱湖": "Inle Lake",
  "莫尔斯比港": "Port Moresby",
  "莫斯塔尔": "Mostar",
  "莫斯科": "Moscow",
  "莫赫悬崖": "Cliffs of Moher",
  "莫雷阿岛": "Moorea",
  "菲斯": "Fes",
  "萨兰达": "Sarandë",
  "萨列马岛": "Saaremaa",
  "萨尔瓦多": "Salvador",
  "萨尔茨堡": "Salzburg",
  "萨拉热窝": "Sarajevo",
  "萨曼纳": "Samaná",
  "萨瓦伊岛": "Savai'i",
  "萨那": "Sana'a",
  "蒂卡尔": "Tikal",
  "蒂豪尼": "Tihany",
  "蒙巴萨": "Mombasa",
  "蒙得维的亚": "Montevideo",
  "蒙特利尔": "Montreal",
  "蒙特哥贝": "Montego Bay",
  "蒙特沃德": "Monteverde",
  "蒲甘": "Bagan",
  "蓝山": "Blue Mountains",
  "蓝洞": "Great Blue Hole",
  "蓝湖": "Blue Lagoon",
  "蓬塔卡纳": "Punta Cana",
  "虎穴寺": "Tiger's Nest Monastery",
  "西哈努克": "Sihanoukville",
  "西奈半岛": "Sinai Peninsula",
  "西安": "Xi'an",
  "西峡湾": "Westfjords",
  "西西里": "Sicily",
  "西贡": "Saigon",
  "西迪布萨义德": "Sidi Bou Said",
  "西雅图": "Seattle",
  "设拉子": "Shiraz",
  "诺维萨德": "Novi Sad",
  "诺西贝": "Nosy Be",
  "贝伦蒂": "Berenty Reserve",
  "贝加尔湖": "Lake Baikal",
  "贝尔格莱德": "Belgrade",
  "贝鲁特": "Beirut",
  "贡德尔": "Gondar",
  "费尔班克斯/北极光": "Fairbanks / Northern Lights",
  "贾斯珀": "Jasper",
  "赫尔辛基": "Helsinki",
  "赫瓦尔岛": "Hvar Island",
  "路易港": "Port Louis",
  "路环": "Coloane",
  "辛特拉": "Sintra",
  "达卡": "Dhaka",
  "达喀尔": "Dakar",
  "达尔文": "Darwin",
  "达纳基尔": "Danakil Depression",
  "迈阿密": "Miami",
  "迦太基": "Carthage",
  "迪利然": "Dilijan",
  "迪拜": "Dubai",
  "迪斯科湾": "Disko Bay",
  "迪纳利国家公园": "Denali National Park",
  "那不勒斯": "Naples",
  "都柏林": "Dublin",
  "都灵": "Turin",
  "采尔马特": "Zermatt",
  "里加": "Riga",
  "里拉修道院": "Rila Monastery",
  "里斯本": "Lisbon",
  "里昂": "Lyon",
  "里约热内卢": "Rio de Janeiro",
  "重庆": "Chongqing",
  "金斯敦": "Kingston",
  "金泽": "Kanazawa",
  "金边": "Phnom Penh",
  "釜山": "Busan",
  "铜峡谷": "Copper Canyon",
  "锡古尔达": "Sigulda",
  "锡吉里亚": "Sigiriya",
  "锡比乌": "Sibiu",
  "镰仓": "Kamakura",
  "长崎": "Nagasaki",
  "长滩岛": "Boracay",
  "门多萨": "Mendoza",
  "阿什哈巴德": "Ashgabat",
  "阿克拉": "Accra",
  "阿克雷里": "Akureyri",
  "阿勒颇": "Aleppo",
  "阿塔卡马沙漠": "Atacama Desert",
  "阿姆斯特丹": "Amsterdam",
  "阿尔乌拉": "AlUla",
  "阿尔加维": "Algarve",
  "阿布扎比": "Abu Dhabi",
  "阿德莱德": "Adelaide",
  "阿拉斯加": "Alaska",
  "阿拉木图": "Almaty",
  "阿斯塔纳": "Astana",
  "阿斯旺": "Aswan",
  "阿比斯库": "Abisko",
  "阿皮亚": "Apia",
  "阿蒂特兰湖": "Lake Atitlán",
  "阿里山": "Alishan",
  "阿里环礁": "Ari Atoll",
  "阿雷纳尔火山": "Arenal Volcano",
  "阿马尔菲": "Amalfi",
  "雅典": "Athens",
  "雅加达": "Jakarta",
  "雅浦岛": "Yap",
  "雷克雅未克": "Reykjavik",
  "霍尼亚拉": "Honiara",
  "霍比特屯": "Hobbiton",
  "青岛": "Qingdao",
  "顺化": "Hue",
  "首尔": "Seoul",
  "香港岛": "Hong Kong Island",
  "马丘比丘": "Machu Picchu",
  "马六甲": "Malacca",
  "马埃岛": "Mahé Island",
  "马尔默": "Malmö",
  "马尼拉": "Manila",
  "马德拉岛": "Madeira",
  "马德里": "Madrid",
  "马拉喀什": "Marrakech",
  "马斯喀特": "Muscat",
  "马朱罗": "Majuro",
  "马略卡岛": "Mallorca",
  "马累": "Malé",
  "马赛": "Marseille",
  "马赛马拉": "Maasai Mara",
  "马那瓜": "Managua",
  "高塔特拉山": "High Tatras",
  "高山": "Takayama",
  "魁北克城": "Quebec City",
  "鱼河峡谷": "Fish River Canyon",
  "鸭嘴鱼湖": "Platypus Lake",
  "鹿特丹": "Rotterdam",
  "麦克默多站": "McMurdo Station",
  "麦德林": "Medellín",
  "麦理浩径": "MacLehose Trail",
  "麦纳麦": "Manama",
  "黄山": "Huangshan",
  "黄石公园": "Yellowstone National Park",
  "黄金圈": "Golden Circle",
  "黄金海岸": "Gold Coast",
  "黑河峡谷": "Black River Gorges",
  "龙目岛": "Lombok",
  '🌏 亚洲': '🌏 Asia',
  '🌍 欧洲': '🌍 Europe',
  '🌎 北美洲': '🌎 North America',
  '🌎 南美洲': '🌎 South America',
  '🌍 非洲': '🌍 Africa',
  '🌊 大洋洲': '🌊 Oceania',
  '❄️ 极地': '❄️ Polar Regions',
  '❄️ 南极洲': '❄️ Antarctica',
  '❄️ 北极地区': '❄️ Arctic Region',
'🌎 美洲': '🌎 Americas',
  '美洲': 'Americas',
  '🦘 大洋洲': '🦘 Oceania',
  '大洋洲': 'Oceania',
  '🌏 大洋洲': '🌏 Oceania',
  '极地': 'Polar Regions',
};

export function getDestinationEnglishName(name) {
  if (!name) return null;
  if (DESTINATION_EN[name]) return DESTINATION_EN[name];

  const raw = String(name);
  const cleaned = raw.replace(/^[^A-Za-z0-9\u4e00-\u9fff]+/u, '').trim();

  if (DESTINATION_EN[cleaned]) {
    const prefix = raw.slice(0, raw.indexOf(cleaned)).trim();
    return prefix ? `${prefix} ${DESTINATION_EN[cleaned]}` : DESTINATION_EN[cleaned];
  }

  return null;
}
